# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gl1tchMud < Formula
  desc "gl1tch MUD game world engine"
  homepage "https://github.com/adam-stokes/gl1tch-mud"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.2.0/gl1tch-mud_0.2.0_darwin_amd64.tar.gz"
      sha256 "9e632500788f94f294f9762243db22b798ae8cc0e90165977e447612e06214a9"

      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.2.0/gl1tch-mud_0.2.0_darwin_arm64.tar.gz"
      sha256 "940866d556328d501875a998921a5bb4bd7b4e41baff6797a03966a1af86fcb2"

      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.2.0/gl1tch-mud_0.2.0_linux_amd64.tar.gz"
      sha256 "e6b38e1d5b69fac220f7c9b9459c4ca7bf65db6ca25243a7964bc4a5984dde65"
      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.2.0/gl1tch-mud_0.2.0_linux_arm64.tar.gz"
      sha256 "ad9aae049615a30fbae8c7f8a7f95639a14f3944411d8ca601bedde64af9df1f"
      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
  end

  test do
    assert_predicate bin/"gl1tch-mud", :exist?
  end
end
