# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glitch < Formula
  desc "gl1tch — AI-native terminal task manager"
  homepage "https://github.com/8op-org/gl1tch"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_darwin_amd64.tar.gz"
      sha256 "635fc81f8460578e309d1d3b2e31ad96c7484867ebd853240ab0b9cc28fab8b3"

      define_method(:install) do
        bin.install "glitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_darwin_arm64.tar.gz"
      sha256 "f00c77c7cc0c6cf1dd4d7f86f2b23dc0aa93079fe23deb1877d1288da36aa1e2"

      define_method(:install) do
        bin.install "glitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_linux_amd64.tar.gz"
      sha256 "b8010bb6123c1f3ca16a2215818fa2087c7fdda0927c13900ff5c6c2a2357f3d"
      define_method(:install) do
        bin.install "glitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_linux_arm64.tar.gz"
      sha256 "652c61e3f6245c20560825aed26409e8e3d4280dbce40bf706b4cb3f58004a6b"
      define_method(:install) do
        bin.install "glitch"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glitch --version")
  end
end
