# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gl1tchMud < Formula
  desc "gl1tch MUD game world engine"
  homepage "https://github.com/adam-stokes/gl1tch-mud"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.3.0/gl1tch-mud_0.3.0_darwin_amd64.tar.gz"
      sha256 "1313269ea77d3183c87caa58993a0764f1a79f73d8ab0d9ae444f875f37dc203"

      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.3.0/gl1tch-mud_0.3.0_darwin_arm64.tar.gz"
      sha256 "8e65c6420c78f91426aac769cadb10664798f1b39d2ecb124c6d9b93eed2af3e"

      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.3.0/gl1tch-mud_0.3.0_linux_amd64.tar.gz"
      sha256 "fafed23485c0ac88c4f86fbf0716d60cf6fd1cf806b15548f5c59a9bb65ea825"
      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam-stokes/gl1tch-mud/releases/download/v0.3.0/gl1tch-mud_0.3.0_linux_arm64.tar.gz"
      sha256 "4104e1d9b2f1f9e4428d8506c0eac2b4f7c2e1f293f56cd99aa9ee0a14be71e3"
      define_method(:install) do
        bin.install "gl1tch-mud"
      end
    end
  end

  test do
    assert_predicate bin/"gl1tch-mud", :exist?
  end
end
