# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GlitchGamification < Formula
  desc "gl1tch gamification daemon — achievements, leaderboard, and NPC agent stats"
  homepage "https://github.com/adam-stokes/gl1tch-gamification"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adam-stokes/gl1tch-gamification/releases/download/v0.1.0/glitch-gamification_0.1.0_darwin_amd64.tar.gz"
      sha256 "2c569ff86db9d20a6985f51583c15f6535b75f9d0af8797bd1881a0b59355a55"

      define_method(:install) do
        bin.install "glitch-gamification"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adam-stokes/gl1tch-gamification/releases/download/v0.1.0/glitch-gamification_0.1.0_darwin_arm64.tar.gz"
      sha256 "eb79f843c842db392e8e8232e98963d92a59769bf1f40defa98a1e736de02c39"

      define_method(:install) do
        bin.install "glitch-gamification"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam-stokes/gl1tch-gamification/releases/download/v0.1.0/glitch-gamification_0.1.0_linux_amd64.tar.gz"
      sha256 "ecfbca38161def09f2e7f4baac3b3a19843da61c68952f66d2589877da0d4dd4"
      define_method(:install) do
        bin.install "glitch-gamification"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam-stokes/gl1tch-gamification/releases/download/v0.1.0/glitch-gamification_0.1.0_linux_arm64.tar.gz"
      sha256 "c1d843e0e3aba1b70fb4275e579d777653aaa8bfed1b19bff4933104f290b595"
      define_method(:install) do
        bin.install "glitch-gamification"
      end
    end
  end

  test do
    assert_predicate bin/"glitch-gamification", :exist?
  end
end
