# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glitch < Formula
  desc "gl1tch — AI-native terminal task manager"
  homepage "https://github.com/8op-org/gl1tch"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_darwin_amd64.tar.gz"
      sha256 "d714e82aaf0479d2204b51291facd72b95c0d6baeb68a94b1909ae110783757f"

      define_method(:install) do
        bin.install "glitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_darwin_arm64.tar.gz"
      sha256 "babd92af30881f565ec9a5896bfdff6d1a9e7a926d5dba1f50bd2b763691e962"

      define_method(:install) do
        bin.install "glitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_linux_amd64.tar.gz"
      sha256 "adf837024aa0c2a49c8983301b7f1b3b990e0400d08df94f711b81f1da3f7f9a"
      define_method(:install) do
        bin.install "glitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/8op-org/gl1tch/releases/download/v0.4.0/glitch_0.4.0_linux_arm64.tar.gz"
      sha256 "2c2ccee984c06aad8c703e8f88ce8f1c5c0a010ca680525738db374366ca1ef8"
      define_method(:install) do
        bin.install "glitch"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glitch --version")
  end
end
