# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glitch < Formula
  desc "gl1tch — your GitHub co-pilot"
  homepage "https://8op.org"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/8op-org/gl1tch/releases/download/v1.0.0/glitch_1.0.0_darwin_amd64.tar.gz"
      sha256 "1694e63989c5deba9e7bdfde9888309ee64cca683cb11a2a50c6687450ee60b7"

      define_method(:install) do
        bin.install "glitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/8op-org/gl1tch/releases/download/v1.0.0/glitch_1.0.0_darwin_arm64.tar.gz"
      sha256 "70987940b636d9bd2f02b3a45bbab29a784db31168f03fb6a5285e2aae40321f"

      define_method(:install) do
        bin.install "glitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/8op-org/gl1tch/releases/download/v1.0.0/glitch_1.0.0_linux_amd64.tar.gz"
      sha256 "5e1e7b41bb20072fc64e49ec80ef14a5cafdce51c389d2f26fff7dfb3def1cd9"
      define_method(:install) do
        bin.install "glitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/8op-org/gl1tch/releases/download/v1.0.0/glitch_1.0.0_linux_arm64.tar.gz"
      sha256 "704db3b4a18910e6bac2076245499e7bddeac1db9274ed2736c2f983dcdb808c"
      define_method(:install) do
        bin.install "glitch"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glitch --version")
  end
end
